# Generated by Django 3.1.5 on 2021-01-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='facebook',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='links',
            name='instagram',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='links',
            name='twitter',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='links',
            name='youtube',
            field=models.URLField(default='#'),
        ),
    ]
