# Generated by Django 3.1.5 on 2021-02-02 07:02

import blog.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210202_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=stdimage.models.StdImageField(upload_to=blog.models.get_file_path, verbose_name='Imagem do Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_titulo',
            field=models.CharField(max_length=100, verbose_name='Subtítulo'),
        ),
    ]
