# Generated by Django 3.1.5 on 2021-02-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210202_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='slug',
            field=models.SlugField(blank=True, editable=False, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='slug',
            field=models.SlugField(blank=True, editable=False, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, editable=False, verbose_name='Slug'),
        ),
    ]
