# Generated by Django 3.1.5 on 2021-01-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210128_1700'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Links',
        ),
    ]
