# Generated by Django 3.1.5 on 2021-02-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210202_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=30, unique=True, verbose_name='Tag'),
        ),
    ]
