# Generated by Django 3.1.5 on 2021-02-03 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210202_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='linkedin_link',
        ),
    ]
