# Generated by Django 3.1.5 on 2021-01-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='facebook_link',
            field=models.URLField(blank=True, verbose_name='Link pra compartilhar no Facebook'),
        ),
    ]
