# Generated by Django 3.1.5 on 2021-01-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210128_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='linkedin_link',
            field=models.URLField(blank=True, editable=False),
        ),
    ]
