# Generated by Django 3.1.5 on 2021-01-29 17:26

from django.db import migrations
import stdimage.models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210129_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuario',
            name='foto_de_perfil',
            field=stdimage.models.StdImageField(blank=True, upload_to=usuarios.models.get_file_path, verbose_name='Foto de perfil'),
        ),
    ]
