# Generated by Django 3.1.5 on 2021-02-05 18:34

from django.db import migrations, models
import stdimage.models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customusuario_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='avatar',
            field=stdimage.models.StdImageField(upload_to=usuarios.models.get_file_path, verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='bio',
            field=models.TextField(max_length=150, verbose_name='bio'),
        ),
    ]
