# Generated by Django 3.1.5 on 2021-01-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_customusuario_foto_de_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusuario',
            old_name='foto_de_perfil',
            new_name='avatar',
        ),
    ]
